General:
  l_filters:
    - OpSubPipelineFilter
    - FilterConvertSequence
    - FilterLog

  source : SourceFromFlatArray
  sink : SinkSlices
  n_process : 1

SourceSub:
  type : SourceList
  parms:
    l_data : TO_COMPLETE

# Source
SourceFromFlatArray:
  type: SourceFromFlatArray
  parms:
    file_path: TO_COMPLETE

# Pipeline Filters
OpSubPipelineFilter:
  type: OpSubPipelineFilter
  source: SourceSub
  sink : None
  parms:
    l_filters:
      - FilterConvertMetrics

FilterConvertMetrics:
  type: FilterConvertMetrics
  parms:
    request: TO_COMPLETE

FilterConvertSequence:
  type: FilterConvertSequence
  parms:
    nb_nodes: None
    nb_edges: 1



FilterLog:
  type: FilterLog
  parms:
    output_path: 'out/logs'
    clean_up: True

# Sink
SinkSlices:
  type: SinkSlices
  parms:
    output_path: TO_COMPLETE
    slice_length: 917979
