General:
  l_filters:
    - FilterParamsEncoding
    - FilterClusterParamValues
    - FilterLog
  source : SourceDict
  sink : SinkWeights
  n_process : 1

# Source
SourceDict:
  type: SourceDict
  parms:
    indexes: TO_COMPLETE
    data: TO_COMPLETE

FilterClusterParamValues:
  type: FilterClusterParamValues
  parms:

    
FilterParamsEncoding:
  type: FilterParamsEncoding
  parms:
    nodes_parametrized: TO_COMPLETE

FilterLog:
  type: FilterLog
  parms:
    output_path: 'out/logs'
    clean_up: True

# Sink
SinkWeights:
  type: SinkWeights
  parms:
    output_path: TO_COMPLETE
    output_path_json: TO_COMPLETE