General:
  l_filters: [OpSubPipelineFilter] 
  source : Source_A
  sink : None # Can be None
  n_process : 1


# Source
Source_A:
  type: SourceFromFlatArray
  parms:
    file_path: 'data/sg_t16_test.npy'
    counter_for_test: 1

# Pipeline Filters
OpSubPipelineFilter:
  type: OpSubPipelineFilter
  source: SourceSub
  sink : None
  parms:
    l_filters: [FilterCheckLabel]

SourceSub:
  type : SourceList
  parms:
    l_data : TO_COMPLETE

FilterCheckLabel:
  type: FilterCheckLabel
  parms :
    label_list: TO_COMPLETE

FilterCount_MinEdge:
  type: FilterCount
  parms:
    min: 1
    max: None
    type: 'edge'

FilterCount_MinMaxNode:
  type: FilterCount
  parms:
    min: 5
    max: 60
    type: 'node'
  