General:
  l_filters:
    - OpSubPipelineFilter
    - FilterDof
    - FilterLog

  source : SourceFromFlatArray
  sink : SinkSlices
  n_process : 1


# Source
SourceFromFlatArray:
  type: SourceFromFlatArray
  parms:
    file_path: TO_COMPLETE

# Pipeline Filters
OpSubPipelineFilter:
  type: OpSubPipelineFilter
  source: SourceSub
  sink : None
  parms:
    l_filters:
      - FilterCheckLabel
      - FilterConstraintRefs
      - FilterCount_MinEdge
      - FilterCount_MinMaxNode
      - FilterCheckParamsMetrics_Length
      - FilterCheckParamsMetrics_Angle

SourceSub:
  type : SourceList
  parms:
    l_data : TO_COMPLETE

FilterCheckLabel:
  type: FilterCheckLabel
  parms :
    label_list: TO_COMPLETE

FilterConstraintRefs:
  type: FilterConstraintRefs
  parms:
    max_refs: 2

FilterCount_MinEdge:
  type: FilterCount
  parms:
    min: 1
    type: 'edge'

FilterCount_MinMaxNode:
  type: FilterCount
  parms:
    min: 5
    max: 60
    type: 'node'

FilterCheckParamsMetrics_Length:
  type: FilterCheckParamsMetrics
  parms:
    request: TO_COMPLETE

FilterCheckParamsMetrics_Angle:
  type: FilterCheckParamsMetrics
  parms:
    request: TO_COMPLETE

FilterDof:
  type: FilterDof
  parms:
    max: null

FilterLog:
  type: FilterLog
  parms:
    output_path: 'out/logs'
    clean_up: True

# Sink
SinkSlices:
  type: SinkSlices
  parms:
    output_path: TO_COMPLETE
    slice_length: 917979
